services:
  java-parser:
    image: java-parser:latest
    build:
      context: ./java
      dockerfile: Dockerfile
    volumes:
      - ./input.xml:/app/input.xml
      - ./result:/app/result
    command: ["--input", "input.xml", "--output", "./result/output-java.xml", "-q", "//*[@id*(-1)<2]"]
    restart: "no"
  python-parser:
    image: python-parser:latest
    build:
      context: ./python
      dockerfile: Dockerfile
    volumes:
      - ./input.xml:/app/input.xml
      - ./result:/app/result
    command: ["--input", "input.xml", "--output", "./result/output-python.xml", "-q", "//*[@id*(-1)<2]"]
    restart: "no"
    depends_on:
      - java-parser
  javascript-parser:
    image: javascript-parser:latest
    build:
      context: ./javascript
      dockerfile: Dockerfile
    volumes:
      - ./input.xml:/app/input.xml
      - ./result:/app/result
    command: ["--input", "input.xml", "--output", "./result/output-javascript.xml", "-q", "//*[@id*(-1)<2]"]
    restart: "no"
    depends_on:
      - python-parser